/**
 * Utilitaires pour la gestion des réseaux sociaux et plateformes
 */

/**
 * Obtient le nom d'affichage d'un réseau social à partir de son ID
 * @param networkId - L'ID du réseau social (ex: 'tiktok', 'instagram', etc.)
 * @returns Le nom d'affichage du réseau social ou "Toutes les plateformes" par défaut
 */
export const getNetworkDisplayName = (networkId: string): string => {
  // Si 'all' ou vide, retourner "Toutes les plateformes"
  if (!networkId || networkId === 'all') {
    return 'Toutes les plateformes';
  }

  // Mapping des IDs vers les noms d'affichage
  const networkDisplayNames: Record<string, string> = {
    'tiktok': 'TikTok',
    'instagram': 'Instagram',
    'youtube': 'YouTube',
    'twitter': 'Twitter',
    'facebook': 'Facebook',
    'linkedin': 'LinkedIn',
    'twitch': 'Twitch',
    'blog': 'Blog',
    'article': 'Article',
    'podcast': 'Podcast',
    'newsletter': 'Newsletter',
    'pinterest': 'Pinterest',
    'snapchat': 'Snapchat',
    'discord': 'Discord',
    'telegram': 'Telegram',
    'whatsapp': 'WhatsApp',
    'reddit': 'Reddit',
    'tumblr': 'Tumblr',
    'medium': 'Medium',
    'substack': 'Substack',
    'spotify': 'Spotify',
    'apple-podcasts': 'Apple Podcasts',
    'google-podcasts': 'Google Podcasts',
    'anchor': 'Anchor',
    'clubhouse': 'Clubhouse',
    'behance': 'Behance',
    'dribbble': 'Dribbble',
    'github': 'GitHub',
    'stackoverflow': 'Stack Overflow',
    'quora': 'Quora',
    'vimeo': 'Vimeo',
    'dailymotion': 'Dailymotion',
    'rumble': 'Rumble',
    'odysee': 'Odysee',
    'bitchute': 'BitChute',
    'onlyfans': 'OnlyFans',
    'patreon': 'Patreon',
    'ko-fi': 'Ko-fi',
    'buy-me-a-coffee': 'Buy Me a Coffee',
    'gofundme': 'GoFundMe',
    'kickstarter': 'Kickstarter',
    'indiegogo': 'Indiegogo',
    'etsy': 'Etsy',
    'shopify': 'Shopify',
    'amazon': 'Amazon',
    'ebay': 'eBay',
    'mercari': 'Mercari',
    'poshmark': 'Poshmark',
    'depop': 'Depop',
    'vinted': 'Vinted',
    'grailed': 'Grailed',
    'stockx': 'StockX',
    'goat': 'GOAT',
    'flightclub': 'Flight Club',
    'stadium-goods': 'Stadium Goods',
    'kixify': 'Kixify',
    'sneaker-con': 'Sneaker Con',
    'sneaker-politics': 'Sneaker Politics',
    'sneaker-bot': 'Sneaker Bot',
    'sneaker-head': 'Sneaker Head',
    'sneaker-freaker': 'Sneaker Freaker',
    'sneaker-news': 'Sneaker News',
    'sneaker-bar': 'Sneaker Bar',
    'sneaker-room': 'Sneaker Room',
    'sneaker-palace': 'Sneaker Palace',
    'sneaker-kingdom': 'Sneaker Kingdom',
    'sneaker-empire': 'Sneaker Empire',
    'sneaker-world': 'Sneaker World',
    'sneaker-universe': 'Sneaker Universe',
    'sneaker-galaxy': 'Sneaker Galaxy',
    'sneaker-cosmos': 'Sneaker Cosmos',
    'sneaker-dimension': 'Sneaker Dimension',
    'sneaker-realm': 'Sneaker Realm',
    'sneaker-domain': 'Sneaker Domain',
    'sneaker-territory': 'Sneaker Territory',
    'sneaker-zone': 'Sneaker Zone',
    'sneaker-area': 'Sneaker Area',
    'sneaker-region': 'Sneaker Region',
    'sneaker-province': 'Sneaker Province',
    'sneaker-state': 'Sneaker State',
    'sneaker-country': 'Sneaker Country',
    'sneaker-continent': 'Sneaker Continent',
    'sneaker-planet': 'Sneaker Planet',
    'sneaker-solar-system': 'Sneaker Solar System',
    'sneaker-galaxy-cluster': 'Sneaker Galaxy Cluster',
    'sneaker-supercluster': 'Sneaker Supercluster',
    'sneaker-universe-cluster': 'Sneaker Universe Cluster',
    'sneaker-multiverse': 'Sneaker Multiverse',
    'sneaker-omniverse': 'Sneaker Omniverse',
    'sneaker-megaverse': 'Sneaker Megaverse',
    'sneaker-gigaverse': 'Sneaker Gigaverse',
    'sneaker-teraverse': 'Sneaker Teraverse',
    'sneaker-petaverse': 'Sneaker Petaverse',
    'sneaker-exaverse': 'Sneaker Exaverse',
    'sneaker-zettaverse': 'Sneaker Zettaverse',
    'sneaker-yottaverse': 'Sneaker Yottaverse',
    'sneaker-ronnaverse': 'Sneaker Ronnaverse',
    'sneaker-quettaverse': 'Sneaker Quettaverse',
  };

  // Retourner le nom d'affichage ou le nom par défaut
  return networkDisplayNames[networkId.toLowerCase()] || networkId;
};

/**
 * Vérifie si un réseau social est valide
 * @param networkId - L'ID du réseau social à vérifier
 * @returns true si le réseau social est valide, false sinon
 */
export const isValidNetwork = (networkId: string): boolean => {
  return networkId === 'all' || getNetworkDisplayName(networkId) !== networkId;
};

/**
 * Obtient tous les réseaux sociaux disponibles
 * @returns Un tableau des IDs de réseaux sociaux
 */
export const getAvailableNetworks = (): string[] => {
  return [
    'all',
    'tiktok',
    'instagram',
    'youtube',
    'twitter',
    'facebook',
    'linkedin',
    'twitch',
    'blog',
    'article',
    'podcast',
    'newsletter',
    'pinterest',
    'snapchat',
    'discord',
    'telegram',
    'whatsapp',
    'reddit',
    'tumblr',
    'medium',
    'substack',
    'spotify',
    'apple-podcasts',
    'google-podcasts',
    'anchor',
    'clubhouse',
    'behance',
    'dribbble',
    'github',
    'stackoverflow',
    'quora',
    'vimeo',
    'dailymotion',
    'rumble',
    'odysee',
    'bitchute',
    'onlyfans',
    'patreon',
    'ko-fi',
    'buy-me-a-coffee',
    'gofundme',
    'kickstarter',
    'indiegogo',
    'etsy',
    'shopify',
    'amazon',
    'ebay',
    'mercari',
    'poshmark',
    'depop',
    'vinted',
    'grailed',
    'stockx',
    'goat',
    'flightclub',
    'stadium-goods',
    'kixify',
    'sneaker-con',
    'sneaker-politics',
    'sneaker-bot',
    'sneaker-head',
    'sneaker-freaker',
    'sneaker-news',
    'sneaker-bar',
    'sneaker-room',
    'sneaker-palace',
    'sneaker-kingdom',
    'sneaker-empire',
    'sneaker-world',
    'sneaker-universe',
    'sneaker-galaxy',
    'sneaker-cosmos',
    'sneaker-dimension',
    'sneaker-realm',
    'sneaker-domain',
    'sneaker-territory',
    'sneaker-zone',
    'sneaker-area',
    'sneaker-region',
    'sneaker-province',
    'sneaker-state',
    'sneaker-country',
    'sneaker-continent',
    'sneaker-planet',
    'sneaker-solar-system',
    'sneaker-galaxy-cluster',
    'sneaker-supercluster',
    'sneaker-universe-cluster',
    'sneaker-multiverse',
    'sneaker-omniverse',
    'sneaker-megaverse',
    'sneaker-gigaverse',
    'sneaker-teraverse',
    'sneaker-petaverse',
    'sneaker-exaverse',
    'sneaker-zettaverse',
    'sneaker-yottaverse',
    'sneaker-ronnaverse',
    'sneaker-quettaverse',
  ];
};
