
-- Supprimer toutes les données existantes dans l'ordre correct (en respectant les contraintes de clés étrangères)
DELETE FROM inspiring_content;
DELETE FROM content_examples;
DELETE FROM content_titles;
DELETE FROM exemplary_accounts;
DELETE FROM subcategory_content_templates;
DELETE FROM subcategory_hashtags;
DELETE FROM subcategory_hooks;
DELETE FROM subcategory_metrics;
DELETE FROM category_likes;
DELETE FROM subcategories;
DELETE FROM categories;

-- Créer les nouvelles catégories
INSERT INTO categories (name, color, description) VALUES
('Activisme', 'primary', 'Contenus militants et engagés'),
('Actualités', 'orange', 'Informations et news du moment'),
('Analyse', 'green', 'Décryptages et analyses approfondies'),
('Anecdote', 'pink', 'Petites histoires et récits personnels'),
('Astuce', 'primary', 'Conseils pratiques et astuces utiles'),
('Animation / dessin animé', 'orange', 'Contenus d''animation et dessins animés'),
('Animaux', 'green', 'Contenus sur les animaux'),
('Art', 'pink', 'Créations artistiques et culturelles'),
('Avant / Après', 'primary', 'Transformations et évolutions'),
('Asmr', 'orange', 'Contenus relaxants et apaisants'),
('Astrologie', 'green', 'Horoscopes et contenus astrologiques'),
('Beauty / style', 'pink', 'Beauté et style de vie'),
('Bricolage / DIY', 'primary', 'Projets à faire soi-même'),
('Bts / coulisse', 'orange', 'Behind the scenes et coulisses'),
('Carrière', 'green', 'Conseils professionnels et carrière'),
('Caption', 'pink', 'Contenus axés sur les légendes'),
('Catastrophe / erreur', 'primary', 'Erreurs et catastrophes'),
('Célébrité', 'orange', 'Contenus sur les célébrités'),
('Challenge', 'green', 'Défis et challenges'),
('Cinéma', 'pink', 'Films et industrie cinématographique'),
('Classement / statistique', 'primary', 'Classements et données statistiques'),
('Complotiste', 'orange', 'Théories du complot'),
('Communauté', 'green', 'Contenus communautaires'),
('Conseil', 'pink', 'Conseils et recommandations'),
('Contenu sans visage', 'primary', 'Contenus anonymes sans visage'),
('Critique', 'orange', 'Critiques et avis'),
('Cuisine', 'green', 'Recettes et contenus culinaires'),
('Date marquante', 'pink', 'Événements historiques importants'),
('Danse', 'primary', 'Chorégraphies et contenus de danse'),
('Débat', 'orange', 'Discussions et débats'),
('Défi', 'green', 'Défis personnels et challenges'),
('Dégustation', 'pink', 'Tests de goût et dégustations'),
('Développement personnel', 'primary', 'Croissance personnelle'),
('Divertissement / fun', 'orange', 'Contenus amusants et divertissants'),
('Documentaire', 'green', 'Contenus documentaires'),
('Dilemme', 'pink', 'Situations difficiles et choix'),
('Duo', 'primary', 'Contenus en duo'),
('Éducation', 'orange', 'Contenus éducatifs et pédagogiques'),
('Événement', 'green', 'Couverture d''événements'),
('Exploration', 'pink', 'Découvertes et explorations'),
('Expérience sociale', 'primary', 'Expérimentations sociales'),
('FAQ vidéo', 'orange', 'Questions-réponses en vidéo'),
('Fan account', 'green', 'Comptes de fans'),
('Fun fact', 'pink', 'Faits insolites et amusants'),
('Guide débutant', 'primary', 'Guides pour débutants'),
('Haul', 'orange', 'Présentation d''achats'),
('Histoire', 'green', 'Contenus historiques'),
('Humour', 'pink', 'Contenus humoristiques'),
('Hypothèse', 'primary', 'Théories et hypothèses'),
('Intelligence artificielle', 'orange', 'IA et technologies'),
('Information', 'green', 'Partage d''informations'),
('Influence', 'pink', 'Contenus d''influence'),
('Interview', 'primary', 'Entretiens et interviews'),
('Jeu vidéo', 'orange', 'Gaming et jeux vidéo'),
('Lecture', 'green', 'Livres et contenus littéraires'),
('Lip sync', 'pink', 'Synchronisation labiale'),
('Live', 'primary', 'Contenus en direct'),
('Makeup', 'orange', 'Maquillage et cosmétiques'),
('Makeover', 'green', 'Relookings et transformations'),
('Marketing', 'pink', 'Stratégies marketing'),
('Meme', 'primary', 'Memes et contenus viraux'),
('Micro-trottoir', 'orange', 'Interviews de rue'),
('Mode / fashion', 'green', 'Mode et tendances vestimentaires'),
('Motivation', 'pink', 'Contenus motivationnels'),
('Musique', 'primary', 'Contenus musicaux'),
('Mythe', 'orange', 'Mythes et légendes'),
('Nature', 'green', 'Contenus sur la nature'),
('Nostalgie', 'pink', 'Souvenirs et nostalgie'),
('Option', 'primary', 'Choix et options'),
('Prank', 'orange', 'Blagues et farces'),
('Parodie', 'green', 'Parodies et imitations'),
('Familles', 'pink', 'Contenus familiaux'),
('Photo', 'primary', 'Photographie'),
('Playback', 'orange', 'Contenus en playback'),
('Podcast', 'green', 'Contenus audio et podcasts'),
('Politique', 'pink', 'Actualités politiques'),
('Portrait', 'primary', 'Portraits et présentations'),
('POV', 'orange', 'Point of view'),
('Prévention', 'green', 'Sensibilisation et prévention'),
('Privé', 'pink', 'Contenus personnels'),
('Recommandation', 'primary', 'Conseils et suggestions'),
('Psychologie', 'orange', 'Contenus psychologiques'),
('Reaction', 'green', 'Réactions et commentaires'),
('Rangement', 'pink', 'Organisation et rangement'),
('Recyclage', 'primary', 'Écologie et recyclage'),
('Réalité', 'orange', 'Contenus réalistes'),
('Relation', 'green', 'Relations et amour'),
('Religion', 'pink', 'Contenus religieux'),
('Réseaux sociaux', 'primary', 'Conseils sur les réseaux sociaux'),
('Routine', 'orange', 'Routines quotidiennes'),
('Santé - sport', 'green', 'Santé et fitness'),
('Satisfaisant', 'pink', 'Contenus satisfaisants'),
('Science', 'primary', 'Contenus scientifiques'),
('Science-fiction', 'orange', 'Science-fiction et futurisme'),
('Sketch', 'green', 'Sketchs et courtes scènes'),
('Sondage', 'pink', 'Sondages et votes'),
('Spiritualité', 'primary', 'Contenus spirituels'),
('Statistique', 'orange', 'Données et statistiques'),
('Storytelling', 'green', 'Narration et récits'),
('Technologie', 'pink', 'Technologies et innovations'),
('Témoignage', 'primary', 'Témoignages personnels'),
('Tendance', 'orange', 'Tendances actuelles'),
('Téléréalité', 'green', 'Contenus de téléréalité'),
('Tradition / culture', 'pink', 'Traditions culturelles'),
('Transition', 'primary', 'Transitions et changements'),
('Tuto', 'orange', 'Tutoriels et guides'),
('UGC', 'green', 'User Generated Content'),
('Unboxing', 'pink', 'Déballages de produits'),
('Lifestyle', 'primary', 'Style de vie'),
('Vie personnelle', 'orange', 'Contenus personnels'),
('Vie quotidienne général', 'green', 'Quotidien général'),
('Vente', 'pink', 'Contenus commerciaux'),
('Vidéographie', 'primary', 'Techniques vidéo'),
('Vlog', 'orange', 'Blogs vidéo'),
('Voyage', 'green', 'Voyages et destinations'),
('Autre', 'pink', 'Autres contenus non classés');
