// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
const SUPABASE_URL = "https://eiuhcgvvexoshuopvska.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdWhjZ3Z2ZXhvc2h1b3B2c2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDM5MjMsImV4cCI6MjA2MzkxOTkyM30.OqFLbnFM3A01feA3NmVYXgnDep9yDghPby8HhxcvOqI";

// Configuration pour le rafraîchissement automatique des tokens
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true, // Rafraîchir automatiquement les tokens expirés
    persistSession: true, // Persister la session dans localStorage
    detectSessionInUrl: true, // Détecter la session dans l'URL (pour OAuth)
    // Rafraîchir le token avant qu'il n'expire (5 minutes avant l'expiration)
    // Supabase gère cela automatiquement avec autoRefreshToken
  },
  // Configuration globale pour gérer les erreurs
  global: {
    headers: {
      'x-client-info': 'creatik-web',
    },
  },
});